name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@main
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy black flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check formatting (Black)
        uses: psf/black@stable
        with:
          options: "--check --verbose"

      - name: Check formatting (isort)
        uses: isort/isort-action@v1

      - name: Linting (flake8)
        uses: py-actions/flake8@v2
        
      - name: Linting (mypy)
        run: mypy .

      - name: Test (pytest)
        run: pytest tests
      
          
      